const SELECTOR_TYPE_DOCTOR = "SELECTOR_TYPE_DOCTOR";
const SELECTOR_TYPE_REASON = "SELECTOR_TYPE_REASON";
const SELECTOR_TYPE_PERIOD = "SELECTOR_TYPE_PERIOD";

export {
  SELECTOR_TYPE_DOCTOR,
  SELECTOR_TYPE_REASON,
  SELECTOR_TYPE_PERIOD
};
